version: '3.5'
services:
  api1: # API - Instância 01
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: api1
    network_mode: host #há um gargalo de rede utilizando a rede docker, portanto utilizar a rede em modo host se torna mais eficiente
    volumes:
      - ./:/app
    depends_on:
      - db
    expose:
      - "9091"
    command: bash -c "npm i && npm run dev"
    environment:
      - HTTP_PORT=9091
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: api2
    network_mode: host
    volumes:
      - ./:/app
    depends_on:
      - db
    expose:
      - "9092"
    command: bash -c "npm i && npm run dev"
    environment:
      - HTTP_PORT=9092
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    expose:
      - 9999
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
   image: mysql:8.0
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha
   network_mode: host
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'